# version: '3.9' # This is deprecated and new docker-compose versions will ignore it.

volumes:
  # map the current directory in the host that contains source code and bind it.
  # Make the code available in the container to use for reach services.
  host-source-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .

networks:
  bridge-network:
    driver: bridge

services:
  lab-ansible-service:
    build:
      context: .
      dockerfile: Dockerfile
      # no_cache: true # uncomment this line to force docker to build the image from scratch
    image: lab-ansible-image:latest
    container_name: lab-ansible-container
    env_file: environment.env
    restart: unless-stopped
    volumes:
      - host-source-volume:/workspace:cached # cached is just for mac and on other platforms it's ignored.
    networks:
      - bridge-network
        